stages:
  - build-and-test

default:
  before_script:
    - dnf install -y java maven file

build-and-test-java:
  stage: build-and-test
  tags:
    - linux
  script:
    # Build
    - mvn compile
    - mvn package
    # Run
    - java -cp ./target/postcodes-1.0.2.jar net.iluo.postcodes.Application
    # These files should have now been created
    - file -E points_au.kml points_nz.kml
